title: Economic load dispatch using java
description: Console based java application for ELD

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-include-cache


relative_links:
  enabled: true
  collections: true
include:
    - README.md
    - LICENSE.md
    - COPYING.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - ISSUE_TEMPLATE.md
    - PULL_REQUEST_TEMPLATE.md

remote_theme: just-the-docs/just-the-docs

#theme: just-the-docs
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  auto_ids: true

mermaid:
  version: "10.1.0"
